Translate 1.2.12. Nullish coalescing operator
javascript-tutorial/ru.javascript.info pull request #1105
Opened 2020-09-20 21:15 UTC by vsemozhetbyt

1. Первый коммит добавляет оригинал и обновляет нумерацию директорий дальнейших разделов. Чтобы легче было сравнивать оригинал с переводом, перевод сделан во втором коммите.

2. Перевод ключевого термина.

    Оригинальный термин [имеет давнюю традицию](https://en.wikipedia.org/wiki/Null_coalescing_operator), но при этом его значение и выбор [затемнены даже для носителей языка](https://stackoverflow.com/questions/770186/null-coalescing-operator-what-does-coalescing-mean). Русский [вариант на MDN](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) является попыткой буквального перевода и сбивает с толку, ведь по сути оператор ничего не сливает и не объединяет (особенно с null-значениями), наоборот — он служит для разделения, выбора, различения с `null`.

    Я перебрал и отбросил несколько вариантов перевода не по букве, но по значению:

    - Оператор ненулевого значения — не подходит, поскольку оператор допускает нуль.
    - Оператор непустого значения — не подходит, поскольку оператор допускает пустую строку.
    - Оператор определённого значения — не подходит, поскольку в русском языке это прилагательное имеет также значение "некоторый, какой-то", что в нашем случае скорее противоречит смыслу термина.
    - Оператор выбора установленного значения — показалось слишком длинным.

    В оригинале слово "nullish" подчёркивает двойственность отбрасываемых значений — не только `null`, но и подобное ему `undefined`. Предлагаемый перевод тоже можно считать отвечающим такому требованию: в отличие от `undefined` значение установлено, в отличие от `null` оно есть.

2020-09-20 21:18 UTC, vsemozhetbyt commented
@javascript-tutorial/translate-ru, @iliakan, пожалуйста, посмотрите, это перевод недостающей главы с нуля.

2020-09-20 21:32 UTC, lex111 commented
Я бы воспользоваться тем, как этот оператор переводят в других ЯП –
оператор объединения с null.

пн, 21 сент. 2020 г., 0:18 Vse Mozhe Buty <notifications@github.com>:

> @javascript-tutorial/translate-ru
> <https://github.com/orgs/javascript-tutorial/teams/translate-ru>, @iliakan
> <https://github.com/iliakan>, пожалуйста, посмотрите, это перевод
> недостающей главы с нуля.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/javascript-tutorial/ru.javascript.info/pull/1105#issuecomment-695837782>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABBUIO5K5NDDUZPBWY7TYQ3SGZWTNANCNFSM4RT3KUCQ>
> .
>

2020-09-20 21:35 UTC, vsemozhetbyt commented
Ну, поскольку он уже отошёл от оригинала в одном слове, может, у нас есть шанс сделать его целиком понятным? Я вот совершенно не могу понять, что значит в данном случае объединение с null.

2020-09-20 21:36 UTC, iliakan commented
Мне тоже кажется, что "объединение с null" ближе к тексту и понятнее. "Оператор установленного значения" - вообще неясно, о чем речь.

2020-09-20 21:37 UTC, vsemozhetbyt commented
Хорошо, если большинство за, я изменю. Через большое «не понимаю, хоть убейте»)

2020-09-20 21:39 UTC, iliakan commented
@vsemozhetbyt если взять англ вариант, то null coalescing operator - это как раз "Оператор объединения с null". Просто обычный перевод фразы.

2020-09-20 21:39 UTC, iliakan commented
В PHP аналог называется "Оператор объединения с null "

2020-09-20 21:42 UTC, vsemozhetbyt commented
Я понимаю, что буквальный перевод таков. Но что в данном случае означает объединение? Вы же пишете учебник в том числе для начинающих, не знающих других языков. Как они хотя бы приблизительно поймут, что с чем объединяется? В разделе об этом ничего не говорится, там всё как раз о выборе, разделении и различении.

2020-09-20 21:46 UTC, vsemozhetbyt commented
Заменил на предложенный вариант.

2020-09-20 22:02 UTC, vsemozhetbyt commented
Может, тогда стоит добавить какое-то объяснение в оригинал, вроде предложенных по ссылке в SO? Что-то вроде — объединение в данном случае значит получение одного значения из нескольких.

2020-09-21 07:46 UTC, iliakan requested changes
Пожалуйста, перечитай перевод со свежей головой, как новый человек, обращая внимание на человечность фраз и орфографию/синтаксис.

Видимо, это первый вариант перевода.

2020-09-21 14:25 UTC, vsemozhetbyt commented
/done

2020-09-23 09:01 UTC, iliakan commented
Прошу прощения за задержку, в процессе правки перевода стало очевидно, что оригинальная статья нуждается в больших изменениях по части изложения, обновил ее, пожалуйста, переведите заново. Еще раз извините, что так получилось.

2020-09-23 15:52 UTC, vsemozhetbyt commented
К сожалению, в ближайшем будущем у меня не будет возможности сделать новый перевод. Надеюсь, кто-то сможет найти для этого время. Простите)

2020-09-23 15:52 UTC, closed without merging