Array.prototype.unshift()
javascript-tutorial/ru.javascript.info pull request #1170
Opened 2020-11-02 23:37 UTC by Maxteh

Метод unshift() добавляет один или более элементов в начало массива и возвращает новую длину массива.

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/unshift

2020-11-02 23:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1170) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1170) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=1170) it.</sub>

2020-11-11 22:54 UTC, dandgerson requested changes
можно убрать избыточные повторы, заменив их на контекст

2020-11-11 22:54 UTC, dandgerson commented on 1-js/05-data-types/04-array/article.md
> +: Добавляет элемент в начало массива и возвращает новую длину массива:
```suggestion
: Добавляет элемент в начало массива и возвращает его новую длину:
```

2020-11-11 22:54 UTC, dandgerson commented on 1-js/05-data-types/04-array/article.md
> +- `unshift(...items)` добавляет `items` в начало массива и возвращает новую длину массива.
```suggestion
- `unshift(...items)` добавляет `items` в начало массива и возвращает его новую длину.   
```

2022-02-12 13:17 UTC, iliakan commented
Никогда не видел, чтобы кто-то в реальной жизни использовал эту возможность. Давайте не будем ее упоминать. Только смутит людей.

2022-02-12 13:17 UTC, closed without merging