Различия между параметрами и аргументами функции
javascript-tutorial/ru.javascript.info pull request #1172
Opened 2020-11-13 15:11 UTC by webfoe

2020-11-13 15:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1172) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1172) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=1172) it.</sub>

2020-11-15 00:30 UTC, dandgerson requested changes

2020-11-15 00:30 UTC, dandgerson commented on 1-js/02-first-steps/15-function-basics/article.md
> +ется внутри функции, тогда она перекрывает внешнюю. Например, в коде ниже функция использует локальную переменную `userName`. Внешняя будет проигнорирована:
опечатка?

2020-11-15 22:33 UTC, webfoe commented
да, была опечатка, исправил
/done

2020-12-07 14:22 UTC, iliakan commented
Не согласен

2020-12-07 14:22 UTC, closed without merging