fix some typo, and not only
javascript-tutorial/ru.javascript.info pull request #1538
Opened 2022-03-06 07:43 UTC by Rnbsov

2022-09-06 20:08 UTC, ruslauz requested changes

2022-09-06 20:08 UTC, ruslauz commented on 1-js/04-object-basics/01-object/3-is-empty/_js.view/solution.js
> +    // если цикл запустился, то значит есть свойство
```suggestion
    // если цикл запустился, то значит свойство есть
```

2022-09-06 20:17 UTC, ruslauz requested changes

2022-09-06 20:17 UTC, ruslauz commented on 1-js/04-object-basics/01-object/8-multiply-numeric/task.md
>  P.S. Используйте `typeof` для проверки, что значение свойства числовое.
```suggestion
P.S. Используйте `typeof` для проверки того, что значение свойства числовое.
```

2022-09-07 16:24 UTC, Rnbsov commented
Этот PR также требует принятия #1631, поскольку используются ссылки вроде той что на 128 строке

```md

## Клонирование и объединение, Object.assign [#cloning-and-merging-object-assign]

```

2022-10-15 15:52 UTC, Alexandre887 commented
Много конфликтов. Пожалуйста, отправьте новый PR.

2022-10-15 15:52 UTC, closed without merging