Обновил статью
javascript-tutorial/ru.javascript.info pull request #1552
Opened 2022-03-17 20:38 UTC by Rnbsov

Я исправил некоторые ошибки в статье, в соответствии со статьей из английской редакции 

https://javascript.info/constructor-new

2022-03-31 20:49 UTC, Rnbsov commented
@iliakan

2022-03-31 20:49 UTC, Rnbsov commented
@iliakan

2022-08-25 14:08 UTC, Alexandre887 requested changes
1. Для чего вы переводите фразы из английской версии учебника на русский язык, дословно? Предложения, которые на английском звучат отлично, могут звучать очень плохо на русском. Это следует учитывать, если вы редактируете содержание русской версии учебника, в соответствии с английской версией.
2. Для чего вы заменяете "т.д" на "так далее"? На мой взгляд, это совершенно бессмысленные правки, т.к можно использовать _оба варианта_.
3. Для чего вы заменяете русские имена в статье на английские? ("Вася" => "John")
То же самое — бессмысленные правки.

Словом, замечаний очень много, прошу рассмотреть мои корректировки. Пока что Pull Request не может быть принят.

2022-08-26 11:59 UTC, Alexandre887 approved these changes
Теперь всё хорошо — можно вносить изменения в сам учебник. 👍

2022-08-26 12:01 UTC, merged