added the missing translation
javascript-tutorial/ru.javascript.info pull request #1553
Opened 2022-03-19 14:44 UTC by Rnbsov

Обновил статью на основе 

https://javascript.info/number

2022-03-24 06:26 UTC, iliakan requested changes
Чуть-чуть поправил исходную статью

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +Тем не менее в реальной жизни мы стараемся не писать длинные последовательности нулей. Мы слишком ленивы для этого. Мы стараемся писать что-то вроде `"1bn"` для миллиарда или `"7.3bn"` для 7 миллиард
1bn → 1 млрд

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +Как и раньше, использование буквы `"е"` может помочь. Если мы хотели бы избежать явного написания нулей, мы могли бы сказать – то же самое, что:
Как и раньше, использование `"е"` может помочь. Если мы хотели бы избежать явного написания нулей, мы могли бы записать то же самое как:

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +Обратите внимание, что две точки в `123456..toString(36)` - это не опечатка. Если мы хотим вызвать метод непосредственно на число, как `toString` в примере выше, то нам нужно поставить две точки `..`
на число → на числе

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +: Округление до ближайшего целого: `3.1` становится `3`, `3.6` — `4`, что касается середины: `3,5` тоже округляется до `4`.
Округление до ближайшего целого: `3.1` становится `3`, `3.6` — `4`, среднее значение `3.5` тоже округлится до `4`.

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +К примеру, у нас есть `1.2345` и мы хотим округлить число до 2-х знаков после запятой, получив только `1.23`.
"оставить" тут ок

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +    Например, чтобы округлить число до второго знака после запятой, мы можем умножить число на `100` (или на большую степень 10), вызвать функцию округления и разделить обратно.
убери плиз `(или на большую степень 10)`

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +    Мы можем преобразовать полученное значение в число, используя унарный оператор `+` или `Number()` вызов: `+num.toFixed(5)`.
Мы можем преобразовать полученное значение в число, используя унарный оператор `+` или `Number()`, например написать `+num.toFixed(5)`.

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +Если число слишком большое, оно переполнит 64-битное хранилище, что потенциально вернёт бесконечность:
Если число очень большое, оно может переполнить 64-битное хранилище, и превратиться в специальное числовое значение "бесконечность" `Infinity`:

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +Рассмотрим этот (ложный!) тест:
Посмотрите на это (ложное!) сравнение:

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +Странно! Что же это тогда, если не` 0,3`?
откуда запятая в `0.3`?

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +Oй! Здесь есть больше последствий, чем неправильное сравнение. Представьте, что вы создаёте сайт электронных покупок, и посетитель кладёт товары стоимостью `$0.10` и `$0.20` в свою корзину. Общая сум
Вот это убери плиз  "Здесь есть больше последствий, чем неправильное сравнение"

В остальном оставь как было.

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +Число хранится в памяти в двоичном виде, в виде последовательности битов – единиц и нулей. Но такие дроби, как `0.1`, `0.2`, которые выглядят простыми в десятичной системе счисления, на самом деле яв
Может лучше так?

Число хранится в памяти в двоичном виде, как последовательность битов - единиц и нулей. Но дроби, такие как `0.1`, `0.2`, которые выглядят довольно просто в десятичной системе счисления, на самом деле являются бесконечной дробью в двоичной форме.

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +Таким образом, деление на степень `10` гарантированно хорошо работает в десятичной системе счисления, но деление на `3` - нет. По той же причине в двоичной системе счисления гарантированно работает д
Что такое `0.1`?  Это единица, делённая на десять `1/10`, одна десятая. В десятичной системе счисления такое значение легко записать. А сравните с одной третьей `1/3`. Она станет бесконечной дробью  `0.33333(3)`.

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +Мы также можем временно умножить числа на 100 (или большее число), чтобы превратить их в целые числа, выполнить математику, а затем разделить обратно. Тогда когда мы совершаем математические операции
Было ок.
"выполнить математику" - не говорят

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +Иногда мы могли бы попытаться вообще избежать дробей. Например, если мы имеем дело с магазином, то мы можем хранить цены в центах вместо долларов. Но что, если мы применим скидку в размере 30%? На пр
Иногда можно попробовать полностью отказаться от дробей. Например, если мы в нашем интернет-магазине начнём использовать центы вместо долларов. Но что будет, если мы применим скидку 30%? На практике далеко не всегда можно полностью избавиться от дробей. Просто используйте округление, чтобы отрезать "хвосты", когда надо.

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +````smart header="Забавная вещь"
Забавный пример - лучше

2022-03-24 06:26 UTC, iliakan commented on 1-js/05-data-types/02-number/article.md
> +// Здравствуйте! Я - самовозрастающее число!
Было ок, зачем менять?

2022-03-24 06:26 UTC, iliakan commented
Там я остановился в правках, дальше сам почитай плиз.

Ни к чему переделывать перевод на точную кальку с английского, если текст и так хороший.

2022-03-24 07:00 UTC, Rnbsov commented on 1-js/05-data-types/02-number/article.md
> +Тем не менее в реальной жизни мы стараемся не писать длинные последовательности нулей. Мы слишком ленивы для этого. Мы стараемся писать что-то вроде `"1bn"` для миллиарда или `"7.3bn"` для 7 миллиард
?

Тем не менее в реальной жизни мы стараемся не писать длинные последовательности нулей. Мы слишком ленивы для этого. Мы стараемся писать что-то вроде `"1bn"` для **_1_** миллиарда или `"7.3bn"` для 7 миллиардов 300 миллионов. То же самое верно и для большинства больших чисел.

Вроде этого?

2022-03-24 07:06 UTC, Rnbsov commented on 1-js/05-data-types/02-number/article.md
> +К примеру, у нас есть `1.2345` и мы хотим округлить число до 2-х знаков после запятой, получив только `1.23`.
Мне кажется тут "получив" звучит лучше

![image](https://user-images.githubusercontent.com/73550760/159861109-6890c17e-d20c-4226-a824-bbcc6cdfb5ca.png)

А если "оставить" то лучше уже "оставив" тогда

2022-03-24 07:08 UTC, ruslauz commented on 1-js/05-data-types/02-number/article.md
> +Тем не менее в реальной жизни мы стараемся не писать длинные последовательности нулей. Мы слишком ленивы для этого. Мы стараемся писать что-то вроде `"1bn"` для миллиарда или `"7.3bn"` для 7 миллиард
@Rnbsov исправьте пожалуйста английские сокращения на русские. Учебник расчитан на русскоязычную аудиторию.

2022-03-24 07:56 UTC, Rnbsov commented on 1-js/05-data-types/02-number/article.md
> +Тем не менее в реальной жизни мы стараемся не писать длинные последовательности нулей. Мы слишком ленивы для этого. Мы стараемся писать что-то вроде `"1bn"` для миллиарда или `"7.3bn"` для 7 миллиард
Ок ок

2022-03-24 07:59 UTC, Rnbsov commented
/done

2022-08-23 23:37 UTC, Alexandre887 commented on 1-js/05-data-types/02-number/article.md
> +К примеру, у нас есть `1.2345` и мы хотим округлить число до 2-х знаков после запятой, получив только `1.23`.
```suggestion
К примеру, у нас есть `1.2345` и мы хотим округлить число до 2-х знаков после запятой, оставив только `1.23`.
```

2023-07-27 15:34 UTC, closed without merging