Class inheritance
javascript-tutorial/ru.javascript.info pull request #1629
Opened 2022-05-07 10:24 UTC by Rnbsov

2022-06-17 19:41 UTC, ruslauz commented on 1-js/09-classes/02-class-inheritance/article.md
> +Синтаксис создания класса допускает указывать после `extends` не только класс, но и любое выражение после `extends`.
Здесь лучше вернуть исходный вариант

2022-06-17 19:44 UTC, ruslauz commented on 1-js/09-classes/02-class-inheritance/article.md
> +Но если мы укажем наш собственный метод в `Rabbit`, например `stop()`, то вместо него будет использоваться он:
Но если мы укажем наш собственный метод в `Rabbit`, например `stop()`, то он будет использоваться взамен родительского:

2022-06-17 19:51 UTC, ruslauz commented on 1-js/09-classes/02-class-inheritance/article.md
> +Если вы нашли этот материал слишком сложным, просто продолжайте, продолжайте читать, а затем вернитесь к нему через некоторое время.
Может быть оставим вместо `просто продолжайте, продолжайте читать` - `просто продолжайте читать`

2022-06-17 19:54 UTC, ruslauz commented on 1-js/09-classes/02-class-inheritance/article.md
> +Хотя, когда мы обращаемся к переопределенному полю в родительском конструкторе, возникает каверзное поведение, сильно отличающееся от большинства других языков программирования.
переопределённому

2022-06-17 19:57 UTC, Rnbsov commented on 1-js/09-classes/02-class-inheritance/article.md
> +Хотя, когда мы обращаемся к переопределенному полю в родительском конструкторе, возникает каверзное поведение, сильно отличающееся от большинства других языков программирования.
Я пропущу потом всё через eye

2022-06-17 20:08 UTC, ruslauz commented on 1-js/09-classes/02-class-inheritance/article.md
> +Если это становится проблемой, ее можно исправить, используя методы или геттеры/сеттеры вместо полей.
её

2022-06-17 20:09 UTC, ruslauz commented on 1-js/09-classes/02-class-inheritance/article.md
> +К счастью, такое поведение проявляется только в том случае, если в родительском конструкторе используется переопределенное поле. Тогда может быть трудно понять, что происходит, поэтому мы объясняем э
переопределённое

2022-06-17 20:10 UTC, ruslauz commented on 1-js/09-classes/02-class-inheritance/article.md
> +В нашем случае `Rabbit` - это производный класс. В нем нет конструктора `constructor()`. Как было сказано ранее, это то же самое, как если бы существовал пустой конструктор только с `super(...args)`.
нём

2022-06-17 20:10 UTC, ruslauz commented on 1-js/09-classes/02-class-inheritance/article.md
> +И это то, чего мы, естественно, ожидаем. Когда родительский конструктор вызывается в производном классе, он использует переопределенный метод.
ереопределённый

2022-06-17 20:11 UTC, ruslauz commented on 1-js/09-classes/02-class-inheritance/article.md
> +Если это еще не ясно, пожалуйста, сравните с методами.
ещё

2022-06-17 20:11 UTC, ruslauz commented on 1-js/09-classes/02-class-inheritance/article.md
> +**Другими словами, родительский конструктор всегда использует свое собственное значение поля, а не переопределенное.**
своё

2022-06-19 13:44 UTC, ruslauz approved these changes

2022-09-18 14:45 UTC, Alexandre887 requested changes

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +- В классах-потомках конструктор обязан вызывать `super(...)`, и (!) делать это перед использованием `this`.
```suggestion
- **Конструкторы в наследуемых классах должны обязательно вызывать `super(...)`, и (!) делать это перед использованием `this`.**.
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +### Переопределение полей класса: каверзное замечание
```suggestion
### Переопределение полей класса: тонкое замечание
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +В этом примечании предполагается, что у вас есть определённый опыт работы с классами, возможно, при работе с другими языками программирования.
```suggestion
В этом подразделе предполагается, что у вас уже есть определённый опыт работы с классами, возможно, в других языках программирования.
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +Если вы нашли этот материал слишком сложным, просто продолжайте читать, а затем вернитесь к нему через некоторое время.
```suggestion
Если вы считаете этот материал слишком трудным для понимания, просто продолжайте читать дальше, а затем вернитесь к нему через некоторое время.
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +Хотя, когда мы обращаемся к переопределённому полю в родительском конструкторе, возникает каверзное поведение, сильно отличающееся от большинства других языков программирования.
```suggestion
Однако, когда мы получаем доступ к переопределенному полю в родительском конструкторе, это поведение отличается от большинства других языков программирования.
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +Здесь класс `Rabbit` расширяет `Animal` и переопределяет поле `name` своим собственным значением.
```suggestion
Здесь, класс `Rabbit` расширяет `Animal` и переопределяет поле `name` своим собственным значением.
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +Что интересно, так это то, что в обоих случаях: `new Animal()` и `new Rabbit()`, `alert` в строке `(*)` показывает `animal`.
```suggestion
Что интересно, в обоих случаях: `new Animal()` и `new Rabbit()`, `alert` в строке `(*)` показывает `animal`.
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +Что в этом странного?
```suggestion
Что же в этом странного?
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +Если это ещё не ясно, пожалуйста, сравните с методами.
```suggestion
Если это ещё не ясно, сравните с методами.
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +Почему есть разница?
```suggestion
Почему же наблюдается разница?
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +Ну, причина в порядке инициализации поля. Поле класса инициализируется:
```suggestion
Что ж, причина заключается в порядке инициализации полей. Поле класса инициализируется:
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +В нашем случае `Rabbit` - это производный класс. В нем нет конструктора `constructor()`. Как было сказано ранее, это то же самое, как если бы существовал пустой конструктор только с `super(...args)`.
```suggestion
В нашем случае `Rabbit` - это производный класс. В нем нет конструктора `constructor()`. Как было сказано ранее, это то же самое, как если бы был пустой конструктор, содержащий только `super(...args)`.
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +Это тонкое различие между полями и методами специфично для JavaScript.
```suggestion
Это тонкое различие между полями и методами характерно для JavaScript.
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +К счастью, такое поведение проявляется только в том случае, если в родительском конструкторе используется переопределённое поле. Тогда может быть трудно понять, что происходит, поэтому мы объясняем э
```suggestion
К счастью, такое поведение проявляется только в том случае, когда переопределенное поле используется в родительском конструкторе. Тогда может быть трудно понять, что происходит, поэтому мы объясняем это здесь.
```

2022-09-18 14:45 UTC, Alexandre887 commented on 1-js/09-classes/02-class-inheritance/article.md
> +Если это становится проблемой, её можно исправить, используя методы или геттеры/сеттеры вместо полей.
```suggestion
Если это становится проблемой, её можно решить, используя методы или геттеры/сеттеры вместо полей.
```

2022-09-18 14:51 UTC, Alexandre887 approved these changes

2022-09-18 14:52 UTC, merged