⚓ add anchors
javascript-tutorial/ru.javascript.info pull request #1631
Opened 2022-05-07 10:50 UTC by Rnbsov

2022-05-09 21:11 UTC, ruslauz commented
Мне кажется нет необходимости в этой правке, так как всё работает должным образом

2022-05-10 08:05 UTC, Rnbsov commented
> Мне кажется нет необходимости в этой правке, так как всё работает должным образом

Мне кажется это не будет лишним, возможно это предотвратит ошибки если люди будут копировать исходники этих статей для перевода на свой язык

2022-09-17 14:16 UTC, Alexandre887 commented on 1-js/05-data-types/03-string/article.md
> +## Сравнение строк [#correct-comparisons]
Если соответствовать англ. версии, здесь не должно быть этого якоря.
[#correct-comparsions] должен быть применён к разделу "Правильное сравнение", нужно исправить.

2022-09-17 15:51 UTC, Alexandre887 requested changes

2022-09-17 15:51 UTC, Alexandre887 commented on 1-js/05-data-types/03-string/article.md
> +    Этот метод находится в [Annex B](https://tc39.es/ecma262/#sec-string.prototype.substr) спецификации языка. Это означает, что его должны поддерживать только браузерные движки Javascript, и использ
```suggestion
    Этот метод находится в [Annex B](https://tc39.es/ecma262/#sec-string.prototype.substr) спецификации языка. Это означает, что его должны поддерживать только браузерные движки JavaScript, и использовать его не рекомендуется. Но на практике он поддерживается везде.
```

2022-09-17 15:52 UTC, Alexandre887 approved these changes

2022-09-17 15:53 UTC, merged