Array methods
javascript-tutorial/ru.javascript.info pull request #1637
Opened 2022-05-14 09:50 UTC by Rnbsov

2022-05-28 08:33 UTC, ruslauz commented
@Rnbsov  Подправь пожалуйста конфликты

2022-05-28 08:42 UTC, ruslauz commented on 1-js/05-data-types/05-array-methods/article.md
> +В процессе работы алгоритм может сравнивать элемент с другими, но он старается сделать как можно меньше сравнений.
В процессе работы алгоритм может сравнивать элемент со множеством других,

2022-08-24 20:51 UTC, ruslauz approved these changes

2022-08-27 13:26 UTC, Alexandre887 requested changes

2022-08-27 13:26 UTC, Alexandre887 commented on 1-js/05-data-types/05-array-methods/article.md
> +Помните алгоритм сравнения [строк](info:string#correct-comparisons)? По умолчанию он сравнивает буквы по их кодам.
```suggestion
Помните алгоритм сравнения [строк](info:string#correct-comparisons)? По умолчанию, он сравнивает буквы по их кодам.
```

2022-08-27 13:26 UTC, Alexandre887 commented on 1-js/05-data-types/05-array-methods/article.md
> +Для многих алфавитов лучше использовать метод `str.localeCompare` для правильной сортировки букв, таких как `Ö`.
```suggestion
Для многих алфавитов лучше использовать метод `str.localeCompare`, для правильной сортировки букв, таких как `Ö`.
```

2022-08-27 13:26 UTC, Alexandre887 commented on 1-js/05-data-types/05-array-methods/article.md
> +Например, давайте отсортируем несколько стран по-немецки:
```suggestion
Например, давайте отсортируем несколько стран на немецком языке:
```

2022-08-27 13:26 UTC, Alexandre887 commented on 1-js/05-data-types/05-array-methods/article.md
> +alert( countries.sort( (a, b) => a.localeCompare(b) ) ); // Andorra,Österreich,Vietnam (верно!)
```suggestion
alert( countries.sort( (a, b) => a.localeCompare(b) ) ); // Andorra,Österreich,Vietnam (правильно!)
```

2022-08-27 13:26 UTC, Alexandre887 commented on 1-js/05-data-types/05-array-methods/article.md
> +  Эти методы ведут себя примерно как операторы `||` и `&&`: если `fn` возвращает истинное значение, `arr.some()` немедленно возвращает `true` и останавливает перебор остальных элементов; если `fn` во
```suggestion
  Эти методы ведут себя примерно так же, как операторы `||` и `&&`: если `fn` возвращает истинное значение, `arr.some()` немедленно возвращает `true` и останавливает перебор остальных элементов; если `fn` возвращает ложное значение, `arr.every()` немедленно возвращает `false` и также прекращает перебор остальных элементов.
```

2022-08-27 13:30 UTC, Alexandre887 approved these changes
👍

2022-08-27 13:32 UTC, merged