👾 smth
javascript-tutorial/ru.javascript.info pull request #1667
Opened 2022-06-19 12:56 UTC by Rnbsov

2022-06-19 13:58 UTC, ruslauz commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +- [CharacterData](https://dom.spec.whatwg.org/#interface-characterdata) -- "абстрактным" класс, он наследуется:
абстрактный

2022-08-26 19:54 UTC, Alexandre887 requested changes

2022-08-26 19:54 UTC, Alexandre887 commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +    Он обеспечивает базовую функциональность: `parentNode`, `nextSibling`, `childNodes` и т.д. (это геттеры). Объекты класса `Node` никогда не создаются. Но есть определённые классы узлов, которые на
```suggestion
    Он обеспечивает базовую функциональность: `parentNode`, `nextSibling`, `childNodes` и т.д. (это геттеры). Объекты класса `Node` никогда не создаются. Но есть определённые классы узлов, которые наследуются от него (и следовательно наследуют функционал `Node`).
```

2022-08-26 19:54 UTC, Alexandre887 commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +- [CharacterData](https://dom.spec.whatwg.org/#interface-characterdata) -- "абстрактный" класс, он наследуется:
```suggestion
- [CharacterData](https://dom.spec.whatwg.org/#interface-characterdata) -- "абстрактный" класс. Вот, кем он наследуется:
```

2022-08-26 19:54 UTC, Alexandre887 commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +    - [Text](https://dom.spec.whatwg.org/#interface-text) -- класс, соответствующий тексту внутри элементов, например `Hello` в `<p>Hello</p>`.
```suggestion
    - [Text](https://dom.spec.whatwg.org/#interface-text) -- класс, соответствующий тексту внутри элементов. Например, `Hello` в `<p>Hello</p>`.
```

2022-08-26 19:54 UTC, Alexandre887 commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +    Он обеспечивает навигацию на уровне элементов: `nextElementSibling`, `children` и методы поиска: `getElementsByTagName`, `querySelector`.
```suggestion
    Он обеспечивает навигацию на уровне элементов: `nextElementSibling`, `children`.
    А также и методы поиска элементов: `getElementsByTagName`, `querySelector`.
```

2022-08-26 19:54 UTC, Alexandre887 commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +    От него наследуют конкретные элементы:
```suggestion
    От него наследуются конкретные элементы:
```

2022-08-26 19:54 UTC, Alexandre887 commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Существует множество других тегов со своими собственными классами, которые могут иметь определенные свойства и методы, в то время как некоторые элементы, такие как `<span>`, `<section>`, `<article>`,
```suggestion
Также существует множество других тегов со своими собственными классами, которые могут иметь определенные свойства и методы, в то время как некоторые элементы, такие как `<span>`, `<section>` и `<article>`, не имеют каких-либо определенных свойств, поэтому они являются экземплярами класса `HTMLElement`.
```

2022-08-26 19:54 UTC, Alexandre887 commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +  // давайте проверим: какой тип узла находится в elem?
```suggestion
  // давайте разберёмся: какой тип узла находится в elem?
```

2022-08-28 21:07 UTC, Alexandre887 approved these changes

2022-08-28 21:09 UTC, merged