Добавлено уточнение касательно абсолютных путей
javascript-tutorial/ru.javascript.info pull request #1708
Opened 2022-08-13 09:04 UTC by KhokhlovKirill

- Добавлено уточнение касательно абсолютных путей в разделе /1-js/02-first-steps/01-hello-world в строке 73

2022-08-13 09:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1708) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1708) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=1708) it.</sub>

2022-08-24 12:49 UTC, Alexandre887 approved these changes

2022-08-24 12:58 UTC, Alexandre887 commented
Весьма неплохая правка. Она будет принята в этой версии учебника, но, нужно добавить её и в английскую версию, чтобы она потом пошла во все остальные репозитории учебника на других языках. Если вы владеете английским, пожалуйста, отправьте Pull Request в [en.javascript.info](https://github.com/javascript-tutorial/en.javascript.info).

P.S. Не нужно открывать и закрывать Pull Request по 10 раз, это не повлияет на скорость принятия правок.

2022-08-24 20:34 UTC, ruslauz commented on 1-js/02-first-steps/01-hello-world/article.md
> +Здесь `/path/to/script.js` - это абсолютный путь, который указывается от корневой папки до необходимого файла. Корневой папкой может являться корень диска или корень сайта, в зависимости от условий р
```suggestion
Здесь `/path/to/script.js` - это абсолютный путь от корневой папки до необходимого файла. Корневой папкой может являться корень диска или корень сайта, в зависимости от условий работы сайта. Также можно указать относительный путь от текущей страницы. Например, `src="script.js"` или `src="./script.js"` будет означать, что файл `"script.js"` находится в текущей папке.
```

2022-08-25 18:56 UTC, Alexandre887 commented on 1-js/02-first-steps/01-hello-world/article.md
> +Здесь `/path/to/script.js` - это абсолютный путь, который указывается от корневой папки до необходимого файла. Корневой папкой может являться корень диска или корень сайта, в зависимости от условий р
В таком случае лучше запрашивать изменения, чем оставлять комментарий, на мой взгляд.

![image](https://user-images.githubusercontent.com/74434545/186746107-d28ff1bc-30b2-48b8-9271-fc2765949e38.png)

2022-08-26 12:39 UTC, ruslauz requested changes

2022-08-26 12:39 UTC, ruslauz commented on 1-js/02-first-steps/01-hello-world/article.md
> +Здесь `/path/to/script.js` - это абсолютный путь, который указывается от корневой папки до необходимого файла. Корневой папкой может являться корень диска или корень сайта, в зависимости от условий р
```suggestion
Здесь `/path/to/script.js` - это абсолютный путь от корневой папки до необходимого файла. Корневой папкой может являться корень диска или корень сайта, в зависимости от условий работы сайта. Также можно указать относительный путь от текущей страницы. Например, `src="script.js"` или `src="./script.js"` будет означать, что файл `"script.js"` находится в текущей папке.
```

2022-08-26 13:00 UTC, KhokhlovKirill commented
А как можно внести изменения без открытия нового Pull Request?

2022-08-26 13:01 UTC, KhokhlovKirill commented on 1-js/02-first-steps/01-hello-world/article.md
> +Здесь `/path/to/script.js` - это абсолютный путь, который указывается от корневой папки до необходимого файла. Корневой папкой может являться корень диска или корень сайта, в зависимости от условий р
@ruslauz , А как можно внести изменения без открытия нового Pull Request?

2022-08-26 14:05 UTC, Alexandre887 commented on 1-js/02-first-steps/01-hello-world/article.md
> +Здесь `/path/to/script.js` - это абсолютный путь, который указывается от корневой папки до необходимого файла. Корневой папкой может являться корень диска или корень сайта, в зависимости от условий р
> А как можно внести изменения без открытия нового Pull Request?

![image](https://user-images.githubusercontent.com/74434545/186921249-d58e399d-655e-4d5a-81eb-ae1b8868310d.png)

И ещё: https://github.com/javascript-tutorial/ru.javascript.info/pull/1708#issuecomment-1225692230

2022-08-26 14:12 UTC, KhokhlovKirill commented on 1-js/02-first-steps/01-hello-world/article.md
> +Здесь `/path/to/script.js` - это абсолютный путь, который указывается от корневой папки до необходимого файла. Корневой папкой может являться корень диска или корень сайта, в зависимости от условий р
@Alexandre887 Этой кнопки нет. Скорее всего потому что я удалил репозиторий из которого делал Pull Request

2022-08-26 14:21 UTC, Alexandre887 commented on 1-js/02-first-steps/01-hello-world/article.md
> +Здесь `/path/to/script.js` - это абсолютный путь, который указывается от корневой папки до необходимого файла. Корневой папкой может являться корень диска или корень сайта, в зависимости от условий р
@KhokhlovKirill, В таком случае, если вы не против, я закрою этот Pull Request, а вы отправите новый, с правками от @ruslauz.

2022-08-26 14:25 UTC, KhokhlovKirill commented on 1-js/02-first-steps/01-hello-world/article.md
> +Здесь `/path/to/script.js` - это абсолютный путь, который указывается от корневой папки до необходимого файла. Корневой папкой может являться корень диска или корень сайта, в зависимости от условий р
Да, хорошо. Сейчас отправлю новый Pull Request.

2022-08-26 14:28 UTC, closed without merging