Closure
javascript-tutorial/ru.javascript.info pull request #1728
Opened 2022-09-04 17:03 UTC by Rnbsov

2022-09-06 20:03 UTC, ruslauz requested changes

2022-09-06 20:03 UTC, ruslauz commented on 1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
> +Такие ситуации часто встречаются как в браузерной, так и в серверной разработке. Функция может быть запланирована для выполнения позже, чем она была создана, например, после действия пользователя или
```suggestion
Такие ситуации часто встречаются как в браузерной, так и в серверной разработке. Функция может быть запланирована для выполнения позже, чем она была создана, например после действия пользователя или сетевого запроса.

```

2022-09-06 20:11 UTC, ruslauz approved these changes

2022-09-06 20:14 UTC, ruslauz commented on 1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
> +Такие ситуации часто встречаются как в браузерной, так и в серверной разработке. Функция может быть запланирована для выполнения позже, чем она была создана, например, после действия пользователя или
Всё таки у меня есть сомнения по поводу необходимости запятой после слова `например`

2022-09-06 20:18 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
> +Такие ситуации часто встречаются как в браузерной, так и в серверной разработке. Функция может быть запланирована для выполнения позже, чем она была создана, например, после действия пользователя или
@ruslauz `...чем она была создана: например, после действия пользователя или сетевого запроса`

2022-09-06 20:22 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
> +Такие ситуации часто встречаются как в браузерной, так и в серверной разработке. Функция может быть запланирована для выполнения позже, чем она была создана, например, после действия пользователя или
Или же `...чем она была создана. Например, после действия пользователя или сетевого запроса`.

2022-09-06 20:24 UTC, ruslauz commented on 1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
> +Такие ситуации часто встречаются как в браузерной, так и в серверной разработке. Функция может быть запланирована для выполнения позже, чем она была создана, например, после действия пользователя или
Кажется, что запятая после `создана`  - это нормально

2022-09-06 20:31 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/1-closure-latest-changes/task.md
> +Такие ситуации часто встречаются как в браузерной, так и в серверной разработке. Функция может быть запланирована для выполнения позже, чем она была создана, например, после действия пользователя или
Я больше склоняюсь к тому, что запятая после `например` не требуется. Но, в любом случае, мы можем просто видоизменить структуру предложения, закончив его после "создана", как я показал во втором примере. А уже тогда, "например" во всех случаях выделяется запятой в начале предложения, т.к является вводным словом.

2022-09-17 16:51 UTC, Alexandre887 requested changes

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +```smart header="Здесь мы поговорим о переменных `let/const`"
```suggestion
```smart header="Здесь мы будем говорить о переменных `let/const`"
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +Для `if`, `for`, `while` и так далее. Переменные, объявленные в `{...}`, также видны только внутри:
```suggestion
Для `if`, `for`, `while` и т.д., переменные, объявленные в `{...}`, также видны только внутри:
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +let message = "Goodbye"; // Error: variable already declared
```suggestion
let message = "Goodbye"; // Ошибка: переменная уже объявлена
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +alert(phrase); // Error, нет такой переменной!
```suggestion
alert(phrase); // Ошибка: нет такой переменной!
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +Здесь, после завершения `if`, `alert` внизу не увидит phrase`, отсюда и ошибка.
```suggestion
Здесь, после завершения `if`, `alert` внизу не увидит `phrase`, отсюда и ошибка.
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +Это здорово, так как позволяет нам создавать локальные переменные блока, специфичные для ветви `if`.
```suggestion
Это замечательно, поскольку это позволяет нам создавать блочно-локальные переменные, специфичные для ветви `if`.
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +alert(i); // Error, нет такой переменной!
```suggestion
alert(i); // Ошибка: нет такой переменной!
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +Что ещё интереснее, вложенная функция может быть возвращена: либо в качестве свойства нового объекта (если внешняя функция создаёт объект с методами), либо сама по себе. И затем может быть использова
```suggestion
Что ещё интереснее, вложенная функция может быть возвращена: либо в качестве свойства нового объекта (если внешняя функция создаёт объект с методами), либо сама по себе. И затем она может быть использована в любом другом месте. Не важно, где, она всё так же будет иметь доступ к тем же внешним переменным.
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +Ниже `makeCounter` создает функцию "счетчик", которая возвращает следующее число при каждом вызове:
```suggestion
Ниже `makeCounter` создает функцию "счётчик", которая возвращает следующее число при каждом вызове:
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +Как это работает? Если мы создадим несколько счетчиков, будут ли они независимыми? Что здесь происходит с переменными?
```suggestion
Как это работает? Если мы создадим несколько счётчиков, будут ли они независимыми? Что здесь происходит с переменными?
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +Насколько я хотел бы избежать низкоуровневых языковых деталей, любое понимание без них было бы ограниченным и неполным, так что будьте готовы.
```suggestion
Как бы мне ни хотелось избежать низкоуровневых деталей языка, любое объяснение без них будет недостаточным и неполным, так что приготовьтесь.
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +Для ясности объяснение разделено на несколько этапов.
```suggestion
Для большей наглядности объяснение разбито на несколько этапов.
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +## Лексическое Окружение
```suggestion
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +В JavaScript при каждом выполнении функции, у блока кода и скрипта есть связанный с ними внутренний (скрытый) объект, называемый *лексическим окружением* `LexicalEnvironment`.
```suggestion
В JavaScript, при каждом выполнении функции, у блока кода `{...}` и скрипта есть связанный с ними внутренний (скрытый) объект, называемый *лексическим окружением* `LexicalEnvironment`.
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
>  **"Переменная" -- это просто свойство специального внутреннего объекта: Environment Record. "Получить или изменить переменную", означает, "получить или изменить свойство этого объекта".**
```suggestion
**"Переменная" -- это просто свойство специального внутреннего объекта, `Environment Record`. "Получить или изменить переменную", означает, "получить или изменить свойство этого объекта".**
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +К примеру, в этом простом коде не содержащеего функций, только одно лексическое окружение:
```suggestion
К примеру, в этом простом коде без функций, только одно лексическое окружение:
```

2022-09-17 16:51 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +По мере того, как код начинает выполняться и продолжается, Лексическое окружение изменяется.
```suggestion
По мере того, как код начинает выполняться и продолжается, лексическое окружение изменяется.
```

2022-09-17 16:57 UTC, Alexandre887 commented
А где подразделы "Этап 2", "Этап 3", "Этап 4", в разделе "Лексическое окружение"? Ещё раз внимательно пересмотрите все ваши правки и закончите перевод.

2022-09-17 17:01 UTC, Rnbsov commented
> А где подразделы "Этап 2", "Этап 3", "Этап 4", в разделе "Лексическое окружение"? Ещё раз внимательно пересмотрите все ваши правки и закончите перевод. 
> Пока что изменю PR на Draft PR.

В этих этапах используются svgs которых нет, либо они требуют обновки

2022-09-17 17:07 UTC, Alexandre887 commented
> > А где подразделы "Этап 2", "Этап 3", "Этап 4", в разделе "Лексическое окружение"? Ещё раз внимательно пересмотрите все ваши правки и закончите перевод.
> > Пока что изменю PR на Draft PR.
> 
> В этих этапах используются svgs которых нет, либо они требуют обновки

Понятно, ну тогда пусть этот PR пока что остается в качестве черновика. Потом пометите как "ready for review", когда будет возможность.

2023-07-27 15:34 UTC, closed without merging