Proofreading
javascript-tutorial/ru.javascript.info pull request #1760
Opened 2022-12-06 07:34 UTC by a-v-gor

1. Добавил отсутствующие строки из английской версии.
2. Слова "индекс" и "позиция" не заменял друг другом, привел по версии страницы на английском.
3. Двойные кавычки вне кода (`"`) заменил на «ёлочки»(`«»`).
4. Исправил некоторые неточности перевода, сделал редакторскую вычитку текста.
5. Доперевел примеры.

2022-12-06 07:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1760) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1760) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=1760) it.</sub>

2022-12-07 20:52 UTC, ruslauz commented on 1-js/05-data-types/05-array-methods/article.md
>  - `arr.includes(item, from)` -- ищет `item`, начиная с индекса `from`, и возвращает `true`, если поиск успешен.
Здесь наверное надо либо добавить символ `--` перед словом "ищет" в первой строке, либо убрать во второй для единообразия

2022-12-07 21:06 UTC, ruslauz requested changes

2022-12-07 21:06 UTC, ruslauz commented on 1-js/05-data-types/05-array-methods/article.md
> +Так, первый аргумент является по сути аккумулятором, который хранит объединенный результат всех предыдущих вызовов функции. По окончании он становится результатом `reduce`.
```suggestion
Так, первый аргумент является по сути аккумулятором, который хранит объединённый результат всех предыдущих вызовов функции. По окончании он становится результатом `reduce`.
```

2022-12-07 21:06 UTC, ruslauz commented on 1-js/05-data-types/05-array-methods/article.md
> +Функция, переданная в `reduce`, использует только два аргумента,  этого обычно достаточно.
```suggestion
Функция, переданная в `reduce`, использует только два аргумента, этого обычно достаточно.
```

2022-12-07 21:06 UTC, ruslauz commented on 1-js/05-data-types/05-array-methods/article.md
> +  - `findIndex` похож на `find`, но возвращает тндекс вместо значения.
```suggestion
  - `findIndex` похож на `find`, но возвращает индекс вместо значения.
```

2022-12-08 04:49 UTC, a-v-gor commented
/done

2022-12-17 22:34 UTC, ruslauz approved these changes

2022-12-18 09:36 UTC, iliakan commented
Изменения русскоязычного текста точно делают статью лучше? 

Мне кажется, что нет, но может это потому что я русский текст писал.

2022-12-27 13:19 UTC, a-v-gor commented
> Изменения русскоязычного текста точно делают статью лучше?
> 
> Мне кажется, что нет, но может это потому что я русский текст писал.

Я старался максимально сохранить авторский стиль (версии на английском языке. Например, «index» – «индекс», «position» – «позиция»), привести к единообразию (часть примеров была переведена на русский, часть - нет. Выбор сделан в пользу перевести оставшееся) и соблюсти правила кириллической типографики (не использовать дефисы вместо тире, применять кавычки-«ёлочки»).

2023-02-03 23:43 UTC, ruslauz commented
👍

2023-02-03 23:43 UTC, merged