correct example
javascript-tutorial/ru.javascript.info pull request #1826
Opened 2023-03-17 09:09 UTC by glitch-surfer

2023-03-17 09:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1826) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1826) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=1826) it.</sub>

2023-03-20 21:55 UTC, ProteinR requested changes

2023-03-20 21:55 UTC, ProteinR commented on 1-js/06-advanced-functions/03-closure/article.md
> +user.sayHi(); // "John" у кода метода "sayHi" есть доступ к внешней переменной "name"
```suggestion
// у кода метода "sayHi" есть доступ к внешней переменной "name"
user.sayHi(); // "John"
```

2023-03-24 11:57 UTC, glitch-surfer commented
/done

2023-03-24 18:58 UTC, Alexandre887 requested changes

2023-03-24 18:58 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +// у кода метода "sayHi" есть доступ к внешней переменной "name"
```suggestion
```

2023-03-24 18:58 UTC, Alexandre887 commented on 1-js/06-advanced-functions/03-closure/article.md
> +user.sayHi(); // "John"
```suggestion
user.sayHi(); // "John" (у кода метода "sayHi" есть доступ к внешней переменной "name")
```

2023-03-26 20:04 UTC, glitch-surfer commented
/done

2023-04-01 14:00 UTC, Alexandre887 approved these changes

2023-04-01 14:01 UTC, merged