typeof - разъяснение
javascript-tutorial/ru.javascript.info pull request #1837
Opened 2023-04-14 10:20 UTC by sias32

Немного вводите в заблуждение по поводу написания выражения в typeof. Предлагаю внести ясность

2023-04-14 10:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1837) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1837) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=1837) it.</sub>

2023-04-14 22:22 UTC, Alexandre887 requested changes
Добрый вечер.
Правки действительно имеют место быть, сделал несколько исправлений.
Также в начале, где вы сравниваете `typeof 5` и `typeof(5)`, не помешало бы добавить небольшое объяснение, что в случае, если выражение _не передается_, результат будет одним и тем же.

2023-04-14 22:22 UTC, Alexandre887 commented on 1-js/02-first-steps/05-types/article.md
> +Если передается выражение, то нужно заключать его в скобки т.к. typeof имеет более высокий приоритет, чем бинарные операторы:
```suggestion
Если передается выражение, то нужно заключать его в скобки, т.к. typeof имеет более высокий приоритет, чем бинарные операторы:
```

2023-04-14 22:22 UTC, Alexandre887 commented on 1-js/02-first-steps/05-types/article.md
```suggestion
Другими словами, скобки необходимы для определения типа значения, которое получилось в результате выполнения выражения в них.
```

2023-04-15 07:30 UTC, sias32 reviewed
Внешние правки

2023-04-15 07:43 UTC, sias32 commented
> Также в начале, где вы сравниваете `typeof 5` и `typeof(5)`, не помешало бы добавить небольшое объяснение, что в случае, если выражение _не передается_, результат будет одним и тем же.

Немного не понимаю, что вы имеете в виду

2023-04-15 07:43 UTC, sias32 commented
/done

2023-04-15 07:48 UTC, sias32 reviewed
Внешние правки

2023-04-15 08:47 UTC, Alexandre887 requested changes
Этого будет достаточно.

2023-04-15 08:47 UTC, Alexandre887 commented on 1-js/02-first-steps/05-types/article.md
> +typeof(5) // Выведет "number"
```suggestion
typeof(5) // Также выведет "number"
```

2023-04-15 08:49 UTC, Alexandre887 requested changes

2023-04-15 08:49 UTC, Alexandre887 commented on 1-js/02-first-steps/05-types/article.md
> +Другими словами, скобки необходимы для определения типа значения, которое получилось в результате выполнения выражения в них.
```suggestion
Другими словами, скобки необходимы для определения типа значения, которое получилось в результате выполнения выражения в них.

```

2023-04-15 08:50 UTC, Alexandre887 approved these changes
👍

2023-04-15 08:50 UTC, merged