add "d" flag description
javascript-tutorial/ru.javascript.info pull request #1845
Opened 2023-04-27 19:25 UTC by ilya-rodin

Добавил информацию о новом флаге

2023-04-27 19:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1845) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1845) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=1845) it.</sub>

2023-08-05 20:39 UTC, ruslauz requested changes

2023-08-05 20:39 UTC, ruslauz commented on 9-regular-expressions/01-regexp-introduction/article.md
> +: С этим флагом результат регулярного выражения помещается в массив, который содержит дополнительную информацию о регулярном выражении, например индексы начала и конца подстрок. Этот флаг никак не ме
```suggestion
: С этим флагом результат регулярного выражения помещается в массив, который содержит дополнительную информацию о регулярном выражении, например индексы начала и конца подстрок. Он никак не меняет поведение регулярного выражения, а лишь предоставляет дополнительную информацию
```

2023-08-05 23:16 UTC, Alexandre887 requested changes
- Необходимо перефразировать начало раздела "Флаги":

> Регулярные выражения могут иметь флаги, которые влияют на поиск.
> В JavaScript их всего шесть:

...т.к уже помимо *влияющих* на поиск флагов есть один *не влияющий* флаг.

- В секции "Итого":

> Регулярное выражение состоит из шаблона и необязательных флагов: `g`, `i`, `m`, `u`, `s`, `y`.

...нужно добавить флаг `d`

2023-08-16 19:45 UTC, Alexandre887 requested changes

2023-08-16 19:45 UTC, Alexandre887 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +: С этим флагом результат регулярного выражения помещается в массив, который содержит дополнительную информацию о регулярном выражении, например индексы начала и конца подстрок. Он никак не меняет по
```suggestion
: С этим флагом результат регулярного выражения помещается в массив, который содержит дополнительную информацию о регулярном выражении, например индексы начала и конца подстрок. Этот флаг не меняет поведение регулярного выражения, а лишь предоставляет дополнительную информацию
```

2023-08-16 19:55 UTC, Alexandre887 commented on 9-regular-expressions/01-regexp-introduction/article.md
> +: С этим флагом результат регулярного выражения помещается в массив, который содержит дополнительную информацию о регулярном выражении, например индексы начала и конца подстрок. Этот флаг не меняет п
```suggestion
: С этим флагом результат регулярного выражения помещается в массив, который содержит дополнительную информацию о регулярном выражении, например индексы начала и конца подстрок. Этот флаг не меняет поведение регулярного выражения, а лишь предоставляет дополнительную информацию.
```

2023-08-16 20:45 UTC, Alexandre887 approved these changes

2023-08-16 20:46 UTC, merged