update information about variable declaration and defenition
javascript-tutorial/ru.javascript.info pull request #1858
Opened 2023-07-15 07:21 UTC by lightonce

Думаю, что правильнее указать разницу между _объявлением_ и _определением_ переменной. Это не синонимы, хоть и в данном контексте это не так принципиально.

2023-07-15 07:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1858) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1858) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=1858) it.</sub>

2023-08-02 15:56 UTC, ruslauz approved these changes

2023-08-05 21:11 UTC, Alexandre887 requested changes

2023-08-05 21:11 UTC, Alexandre887 commented on 1-js/02-first-steps/04-variables/article.md
> +Теперь можно поместить (или *определить*) в неё данные, используя оператор присваивания `=`:
```suggestion
Теперь можно поместить в неё данные (другими словами, *определить переменную*), используя оператор присваивания `=`:
```
"определить данные в переменную" звучит как-то не по-русски. На мой взгляд, такой вариант выглядит лучше.

2023-08-05 21:17 UTC, Alexandre887 commented on 1-js/02-first-steps/04-variables/article.md
> +Теперь можно поместить (или *определить*) в неё данные, используя оператор присваивания `=`:
Далее в статье также используется этот термин:

![Screenshot](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/dcbfe4c7-834f-40d9-b70c-7599b4f7a83b)

2023-08-16 19:24 UTC, Alexandre887 approved these changes

2023-08-16 19:24 UTC, merged