написала более понятную формулировку на мой взгляд
javascript-tutorial/ru.javascript.info pull request #1864
Opened 2023-07-20 07:54 UTC by iamlorddop

2023-07-20 07:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1864) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1864) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=1864) it.</sub>

2023-08-02 15:05 UTC, ruslauz requested changes

2023-08-02 15:05 UTC, ruslauz commented on 1-js/09-classes/03-static-properties-methods/article.md
> +Статические методы (static) используются для реализации функций(методов), которые будут принадлежать классу целиком, но при этом не относящимся к каким-то отдельным объектам.
```suggestion
Статические методы используются для реализации функций, которые будут принадлежать классу в целом, но не какому-либо его конкретному объекту.
```

2023-08-02 17:21 UTC, iamlorddop commented
/done

2023-08-02 17:22 UTC, ruslauz approved these changes

2023-08-02 17:23 UTC, ruslauz approved these changes

2023-08-04 13:49 UTC, Alexandre887 requested changes

2023-08-04 13:49 UTC, Alexandre887 commented on 1-js/09-classes/03-static-properties-methods/article.md
> +Статические методы используются для реализации функций, которые будут принадлежать классу в целом, но не какому-либо его конкретному объекту.
```suggestion
Обычно статические методы используются для реализации функций, которые будут принадлежать классу в целом, но не какому-либо его конкретному объекту.
```

Статические методы используются не только для этих целей, отсутствие "обычно" меняет весь смысл предложения.

2023-08-04 13:55 UTC, Alexandre887 approved these changes
👍

2023-08-04 13:55 UTC, merged