Добавила информацию об объекте options
javascript-tutorial/ru.javascript.info pull request #1882
Opened 2023-08-17 06:28 UTC by iamlorddop

Добавила информацию об объекте options в scrollTo, scrollBy, scrollIntoView

2023-08-17 22:25 UTC, Alexandre887 reviewed
Немного изменил добавленный текст, добавил чуть больше информации.

Пара вопросов:

1) Из первоначального текста, про `scrollTo`/`scrollBy`:

   > scrollTo/scrollBy могут иметь options, как аргумент:
   > element.scrollTo(options).
   > options - объект с тремя свойствами:
   > ```js
   > element.scrollTo({`
   >   top: 100,
   >   left: 100,
   >   behavior: "smooth"
   > });
   > ```
   > где behavior: "smooth" означает плавную прокрутку. Принимает значения "auto" или "smooth". По умолчанию "auto" - то есть, без плавной прокрутки.
   > 
   > <ins>**Не поддерживается только в IE.**</ins>

   Не совсем понятно, откуда данная информация (про IE). Из какого она источника? 

2) Из первоначального текста, про `scrollIntoView`:


   > scrollIntoView также может иметь options, как аргумент:
   > element.scrollIntoView(options).
   > options - объект с тремя свойствами:
   > - behavior - Анимация прокрутки. Принимает значения "auto" или "smooth". По умолчанию "auto".
   > - block - Вертикальное выравнивание. Одно из значений: "start", "center", "end" или "nearest". По умолчанию "start".
   > - inline - Горизонтальное выравнивание. Одно из значений: "start", "center", "end" или "nearest". По умолчанию "nearest".
   > ```js
   > elem.scrollIntoView({block: "center", behavior: "smooth"});
   > ```
   ><ins>**behavior: "smooth" не поддерживается в IE и Safari, но начиная с версии 16.0 в Safari появилась поддержка 
   behavior:**</ins>
   ><ins>**"smooth".**</ins>

   Также непонятно, откуда информация про IE. 

   В Safari поддержка `behavior: "smooth"` появилась с [релиза 15.4](https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes#Web-API), но, насколько я понимаю, до сих пор в Safari плавная прокрутка работает не совсем корректно: https://bugs.webkit.org/show_bug.cgi?id=238497

2023-08-19 11:26 UTC, iamlorddop commented
Спасибо за поправки в тексте. 
Вот информация про IE
- [scrollIntoView](https://www.lambdatest.com/web-technologies/scrollintoview#:~:text=Browser%20Support%20for%20scrollIntoView)
- [scroll, scrollTo, scrollBy](https://www.lambdatest.com/web-technologies/element-scroll-methods-support-on-edge-18#:~:text=Show%20more...-,Browser%20Support%20for%20Scroll%20methods%20on%20elements%20(scroll%2C%20scrollTo%2C%20scrollBy),-IE)

2023-08-19 21:50 UTC, Alexandre887 requested changes

2023-08-19 21:50 UTC, Alexandre887 commented on 2-ui/1-document/10-size-and-scroll-window/article.md
> +  - `"smooth"` -- плавно (не поддерживается в Safari)
```suggestion
  - `"smooth"` -- плавно (не поддерживается в IE и в старых версиях Safari)
```

2023-08-19 21:50 UTC, Alexandre887 commented on 2-ui/1-document/10-size-and-scroll-window/article.md
> +<button onclick="window.scrollTo({ top: 500, left: 0, behavior: "smooth" })">window.scrollTo({ top: 500, left: 0, behavior: "smooth" })</button>
```suggestion
<button onclick="window.scrollBy({ top: 500, left: 0, behavior: "smooth" })">window.scrollBy({ top: 500, left: 0, behavior: "smooth" })</button>
```

2023-08-19 21:50 UTC, Alexandre887 commented on 2-ui/1-document/10-size-and-scroll-window/article.md
> +Демонстрация плавной прокрутки страницы (в Safari прокрутка будет мгновенной):
```suggestion
Демонстрация плавной прокрутки страницы:
```

2023-08-19 22:00 UTC, Alexandre887 requested changes

2023-08-19 22:01 UTC, Alexandre887 commented on 2-ui/1-document/10-size-and-scroll-window/article.md
> +- `inline` -- горизонтальное выравнивание (`start`, `center`, `end`, `nearest`). Значение по умолчанию: `nearest`
```suggestion
- `inline` -- горизонтальное выравнивание (`start`, `center`, `end`, `nearest`). Значение по умолчанию: `nearest`

```

2023-08-19 22:02 UTC, Alexandre887 approved these changes
👍

2023-08-19 22:10 UTC, merged