Добавлена типичная ошибка отсутствия запятой
javascript-tutorial/ru.javascript.info pull request #1887
Opened 2023-08-25 19:05 UTC by mecmep

Добавлена типичная ошибка отсутствия после значения в JSON запятой. Также, возможно, стоит добавить ошибку с избыточной запятой после значения.

2023-08-25 19:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1887) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1887) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=1887) it.</sub>

2023-08-26 22:47 UTC, Alexandre887 requested changes
Неплохие идеи, особенно касательно запятой после последнего значения. Это, наверно, *самая* распространённая ошибка

2023-08-26 22:47 UTC, Alexandre887 commented on 1-js/05-data-types/12-json/article.md
> +  "friends": [0,1,2,3]              // Здесь всё в порядке
```suggestion
  "friends": [0,1,2,3]*!*,*/!*              // Ошибка: после последнего свойства запятой не должно быть
```

2023-08-26 22:47 UTC, Alexandre887 commented on 1-js/05-data-types/12-json/article.md
> +  "gender": "male"*!* */!*                 // Ошибка: отсутствует запятая после непоследнего значения
```suggestion
  "gender": "male"*!* */!*                 // Ошибка: отсутствует запятая после непоследнего свойства
```

2023-08-26 22:47 UTC, Alexandre887 commented on 1-js/05-data-types/12-json/article.md
> +  "gender": "male"*!* */!*                 // Ошибка: отсутствует запятая после непоследнего значения
Пара `"ключ": "значение"` — это свойство. На мой взгляд, лучше будет именно так написать.

2023-08-28 10:05 UTC, mecmep commented on 1-js/05-data-types/12-json/article.md
> +  "friends": [0,1,2,3]              // Здесь всё в порядке
```suggestion
  "friends": [0,1,2,3]*!*,*/!*             // Ошибка: не должно быть запятой после последнего свойства
```
Перефразировал комментарий под стиль других комментариев и убрал лишний пробел

2023-08-28 10:07 UTC, mecmep commented on 1-js/05-data-types/12-json/article.md
> +  "gender": "male"*!* */!*                 // Ошибка: отсутствует запятая после непоследнего значения
Возможно. Для меня особой разницы нет. Фактически, оба варианта верны.
Но тогда и в описании _replacer_-а на 187-ой строке кода должно быть написано не "Массив свойств", а "Массив имён свойств".

2023-08-28 10:55 UTC, mecmep commented
/done

2023-08-28 18:30 UTC, Alexandre887 commented on 1-js/05-data-types/12-json/article.md
> +  "gender": "male"*!* */!*                 // Ошибка: отсутствует запятая после непоследнего значения
Да, определение термина «свойство» на самом деле достаточно размыто. Многие руководства и учебники не заостряют внимание на правильности определения. 

Посмотрел касательно replacer'a на MDN:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/6f5921f6-5e83-4783-bea4-d1c3470bfe46)

«свойства "week" и "month"», не «свойства с именами "week" и "month"». Так что не думаю, что оставить «массив свойств» будет серьёзной ошибкой.

2023-08-28 18:31 UTC, merged

2023-08-28 20:39 UTC, mecmep commented on 1-js/05-data-types/12-json/article.md
> +  "gender": "male"*!* */!*                 // Ошибка: отсутствует запятая после непоследнего значения
Но ведь это _properties_ в комментарии относится к _{"week":45,"month":7}_, а не к _["week", "month"]_, в котором используются именно _ключи_ (то есть _имена свойств_, в принятой на странице терминологии).
А то, что _"week" and "month" properties_, а не _properties with names "week" and "month"_, так это, скорее всего, особенности языка.
К тому же, получается, что если оставить «массив свойств» вместо «массив имён свойств» (массив ключей), то продолжится добавление размытости термину «свойство».

2023-08-28 21:43 UTC, Alexandre887 commented on 1-js/05-data-types/12-json/article.md
> +  "gender": "male"*!* */!*                 // Ошибка: отсутствует запятая после непоследнего значения
> Но ведь это properties в комментарии относится к {"week":45,"month":7}, а не к ["week", "month"], в котором используются именно ключи (то есть имена свойств, в принятой на странице терминологии).

Это не меняет сути дела. Говоря о `{"foundation":"Mozilla","model":"box","week":45,"transport":"car","month":7}`, автор раздела на MDN утверждает, что `JSON.stringify()` оставил из этого объекта только:
* «свойство "week"»
* «свойство "month"»

...Хотя правильнее и точнее было бы сказать в этом случае, что `JSON.stringify()` <ins>**оставил только свойства с именами (ключами) "week" и "month"**</ins>.

> А то, что "week" and "month" properties, а не properties with names "week" and "month", так это, скорее всего, особенности языка.

Поднимемся чуть выше по статье на MDN:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/02c2d0a4-f1c9-45fe-9a1a-3f90d481c688)

Здесь уже используется *properties <ins>with name</ins>*, полностью опровергая вашу мысль касательно "особенности языка".

К тому же, исходя из таких суждений, можно сказать, что "массив свойств", а не "массив имён свойств", — это тоже особенность языка, верно?

> К тому же, получается, что если оставить «массив свойств» вместо «массив имён свойств» (массив ключей), то продолжится добавление размытости термину «свойство».

Не подумайте, что я намеренно избегаю принятия этого уточнения, но, раз уж на то пошло, то нужно вносить правки во все статьи. Неважно, оставить «массив свойств» или добавить уточнение, — на общую степень «размытости» это никак не повлияет. Во многих других статьях достаточно неточностей касательно определения термина «свойство», в том числе, даже в статье «Объекты», где, казалось бы, должны быть самые чёткие формулировки.

2023-08-29 20:32 UTC, mecmep commented on 1-js/05-data-types/12-json/article.md
> +  "gender": "male"*!* */!*                 // Ошибка: отсутствует запятая после непоследнего значения
> Здесь уже используется _properties <ins>with name</ins>_, полностью опровергая вашу мысль касательно "особенности языка".

Почему же? Вовсе нет. То, что _properties with names "week" and "month"_ можно сократить в вариант _"week" and "month" properties_, не означает, что аналогичное преобразование применимо и к фразе _properties with name ""_, в которой имя пустое.

> К тому же, исходя из таких суждений, можно сказать, что "массив свойств", а не "массив имён свойств", — это тоже особенность языка, верно?

Если я правильно понял вопрос, то нет, так как гипотетическая особенность одного языка не может означать наличие такой особенности в другом языке.

После немного более подробного изучения той самой статьи на MDN обнаружил про _replacer_ следующее:
> As an array, its elements indicate **the names of the properties** in the object that should be included in the resulting JSON string.

То есть, там есть чёткое указание, что элементы массива обозначают имена свойств.

2023-08-29 23:33 UTC, Alexandre887 commented on 1-js/05-data-types/12-json/article.md
> +  "gender": "male"*!* */!*                 // Ошибка: отсутствует запятая после непоследнего значения
>  properties with names "week" and "month" можно сократить в вариант "week" and "month" properties

Повторюсь: это полностью эквивалентно сокращению «свойства с именами "week" и "month"» в «свойства "week" и "month"». 

> То есть, там есть чёткое указание, что элементы массива обозначают имена свойств.

На эту тему можно дискутировать очень долго, но, всё-таки, не будем забывать, что «свойство» — это абстрактное понятие, использование которого не описывается даже в спецификации языка. Если мы прибегнем к ней:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/803d28e3-b475-453c-9d81-22ce0b3990fa)

...то увидим лишь общее определение. Отсутствует конкретный стандарт, по которому мы можем судить — правильно ли звучит выражение или нет.

MDN — это <ins>документация</ins>. Обычно, при написании документации к чему-либо (будь то ЯП, фреймворк или ещё что-либо), составляется глоссарий терминов, которые в дальнейшем будут использоваться в этой документации. 

На MDN подобный глоссарий есть. Они установили в нём свое описание термина «свойство», исходя из своей точки зрения. И в документации они пользуются <ins>своим</ins> определением этого термина, хотя, бывают и расхождения, я упоминал о них выше.

Так как [learn.javascript.ru](https://learn.javascript.ru) не является ни спецификацией, ни документацией, ни каким-либо стандартом по типу W3C, — соответственно, глоссария здесь нет. Определения терминов приводятся в статьях, где они упоминаются. В последующих статьях, где используются эти термины, могут быть небольшие расхождения (они незначительны и не меняют самого определения термина). 

Если убирать данные расхождения, то, в таком случае, и во всех других статьях, где они есть. Это намного логичнее, чем просто добавить уточнение в одной статье, из всего учебника. Если возвращаться к описанию `replacer`, то придется добавлять не одно уточнение:

![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/a98948cf-f891-42c0-bcb4-8d12cd557186)
![image](https://github.com/javascript-tutorial/ru.javascript.info/assets/74434545/fc031a4f-0253-4d3e-95c1-ef4cf36e5685)