Добавление раздела: WeakRef & FinalizationRegistry
javascript-tutorial/ru.javascript.info pull request #1899
Opened 2023-10-12 10:16 UTC by WOLFRIEND

## Описание

Добавление информации о таких возможностях как `WeakRef` & `FinalizationRegistry`.
Обсуждения и утверждение данного предложения находятся по ссылке:
https://github.com/javascript-tutorial/ru.javascript.info/issues/1898

## Ссылки

## Связанные Issue

2023-10-22 18:47 UTC, Alexandre887 requested changes
Добрый вечер.

Не пугайтесь большого количества правок — в основном это suggested changes, которые можно принять в один клик. 

Также:
- Я оставил комментарии к некоторым строкам кода, т.к не везде понятна ваша мысль.
- Я оставил комментарии к некоторым частям текста, где есть тавтология и/или логические ошибки. Также где-то определённые выражения звучат не совсем по-русски, так что их нужно перефразировать.
- Были ошибки, которые распространяются на весь материал статьи. К примеру, неверное написание определённых слов. В таком случае я не искал и не исправлял эти ошибки во всём тексте, просто оставил комментарий к одному подобному примеру, дальше вы должны будете сами их исправить.

**Обязательно сначала примите suggested changes, а только потом рассматривайте комментарии.** Иногда я оставлял и suggested changes, и комментарий в одной правке, так что <ins>**внимательно**</ins> всё прочтите.

Если мои замечания где-то не совсем понятны, или вы хотите их оспорить, — в Github также можно оставлять к ним комментарии, я получу уведомление и мы обсудим эти вопросы.

В техническую часть материала я пока глубоко не вдавался, сфокусировался на тексте и коде.

В раздел «Типы данных», на мой взгляд, статью будет помещать неправильно. Это очень узконаправленная тема, которая на практике <ins>не</ins> затрагивает 90% всех программистов. Многие спокойно пишут код, даже не зная, что такие возможности были введены в язык. Оно и к лучшему, т.к даже в mdn приведён перечень причин, по которым лучше избегать использования структур, о которых идет речь в статье.
Поэтому, лучше всего будет добавить статью в раздел «Разное», в конец первой части учебника.

В начале статьи можем добавить предостережение, указать в нём причины, которые я привёл выше. Также следует добавить информацию о том, что для прочтения необходимы базовые знания в `DOM`, т.к в статье есть примеры с его использованием.
Но, сейчас это не столь важно. Сосредоточьтесь на рассмотрении моих правок.

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Давайте представим, что мы хотим создать коллаж из 4-х фотографий, выбираем их, и нажимаем кнопку «Create collage».
```suggestion
Давайте представим, что мы хотим создать коллаж из 4 фотографий, выбираем их, и нажимаем кнопку «Create collage».
```

Буквенное падежное окончание для количественных числительных не используется. Мог где-либо пропустить, исправьте во всём тексте.

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +то скачивает его из облака и помещает в кэш для возможного дальнейшего использования.
```suggestion
то скачивает его из облака и помещает в кэш для возможности дальнейшего использования.
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +И так происходит для каждого выбранного изображения.
```suggestion
И так происходит для каждого выбранного изображения:
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Из вывода в консоли видно, какие из фотографий были загружены из облака (синее сообщение с текстом `FETCHED_IMAGE`).
```suggestion
Обратив внимание на вывод в консоли можно увидеть, какие из фотографий были загружены из облака (синее сообщение с текстом `FETCHED_IMAGE`).
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +И наш финализатор выполнился успешно, тем самым удалив ключ, по которому изображение хранилось в кэше, и оповестив нас красным сообщением в консоль.
```suggestion
И наш финализатор выполнился успешно, тем самым удалив ключ, по которому изображение хранилось в кэше. Об этом нас уведомляет красное сообщение в консоли:
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Для этого достаточно снять выделение с не желаемого изображения, выбрать нужное, и ещё раз нажать кнопку "Create collage".
```suggestion
Для этого достаточно снять выделение с ненужного изображения, выбрать желаемое, и ещё раз нажать кнопку "Create collage":
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Но, обратите внимание на зелёное сообщение в консоли с текстом `CACHED_IMAGE`,
```suggestion
Но, обратите внимание на зелёное сообщение в консоли с текстом `CACHED_IMAGE`:
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Это означает, что на момент создания коллажа сборщик мусора ещё не удалил наше изображение, и мы смело использовали его из кэша,
```suggestion
Это означает, что на момент создания коллажа сборщик мусора ещё не удалил наше изображение, и мы смело взяли его из кеша,
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +тем самым сократив количество сетевых запросов и ускорив общее время процесса создания коллажа.
```suggestion
тем самым сократив количество сетевых запросов и ускорив общее время процесса создания коллажа:
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Давайте ещё немного "поиграем", заменив одно из изображений ещё раз и создадим новый коллаж.
```suggestion
Давайте ещё немного "поиграем", заменив одно из изображений ещё раз и создав новый коллаж:
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Снижение нагрузки на сеть составило ~ 75%, впечатляет, не правда ли?
```suggestion
Снижение нагрузки на сеть составило около 75%. Впечатляет, не правда ли?
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Сразу же возникает вполне логичный вопрос: почему бы нам не использовать обычный кэш, где мы можем сами управлять его сущностями, а не полагаться на сборщика мусора?
```suggestion
Сразу же возникает вполне логичный вопрос: почему бы нам не использовать обычный кэш, где мы можем сами управлять его сущностями, а не полагаться на сборщик мусора?
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Всё верно, в большинстве случаев нет необходимости использовать `WeakRef`.
```suggestion
Всё верно, в большинстве случаев нет необходимости использовать `WeakRef` и `FinalizationRegistry`.
```

Полагаю, должно быть так.

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +В данном случае была представлена альтернативная концепция, которая может быть полезной для определенных сценариев.
```suggestion
В данном случае была представлена альтернативная реализация, которая может быть полезной лишь для редких, неординарных сценариев.
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Это, скорее, демонстрация возможности и предоставление основы для собственных размышлений и реализаций.
```suggestion
Это, скорее, демонстрация возможности и предоставление основы для собственных размышлений и исследований.
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Для оптимального взаимодействия, рекомендуем вам открыть демо в новом окне в полноэкранном режиме,
```suggestion
Для оптимального взаимодействия откройте демо в новом окне в полноэкранном режиме,
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +`WeakRef` - предназначенный для создания слабых ссылок на объекты, что позволяет объектам быть удалёнными из памяти сборщиком мусора, если на них больше нет сильных ссылок.
```suggestion
`WeakRef` - предназначен для создания слабых ссылок на объекты, что позволяет им быть удалёнными из памяти сборщиком мусора, если на них больше нет сильных ссылок.
```

2023-10-22 18:47 UTC, Alexandre887 commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +`FinalizationRegistry` - это средство для регистрации колбэков, которые выполняются при уничтожении объектов, на которые больше нет сильных ссылок.
```suggestion
`FinalizationRegistry` - это средство регистрации колбэков, которые выполняются при уничтожении объектов, на которые больше нет сильных ссылок.
```

2023-10-23 06:52 UTC, WOLFRIEND commented
Спасибо большое за правки и предложение.
Я ознакомился и принял ваши suggested changes.
Теперь начинаю работу над вашими комментариями.

2023-10-25 08:22 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +let user = { name: "Aleks" };
Исправил.

2023-10-25 08:23 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +//  в переменной user находится сильная ссылка на объект
Исправил.

2023-10-25 08:25 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +```
Исправил.

2023-10-25 08:26 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Метод `deref()` возвращает объект или `undefined`, если объект больше не доступен.
Исправил.

2023-10-25 08:26 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +`WeakRef` обычно используется для создания кэшей или сопоставлений (mappings), в которых хранятся массивные объекты,
Исправил.

2023-10-25 08:27 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +гарантируя, что простое присутствие объекта в кэше или сопоставлении не гарантирует сохранение этих больших объектов в памяти.
Исправил.

2023-10-25 08:27 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +- `WeakMap` также не подходит для этой цели: они слабы по своим ключам, но в данном случае нам нужна структура данных, которая была бы слабой по значениям.
Исправил.

2023-10-25 08:28 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +const getCachedImg = weakRefCache(fetchImg);
Это абстрактная функция для загрузки изображений. То есть, тут не важны детали её реализации.
Исправил это добавив её и описание.

2023-10-25 08:28 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +- `(5)` Если кэш содержит значение по указанному ключу, и объект `WeakRef` не был удалён сборщиком мусора, возвращаем закэшированный результат.
Исправил.

2023-10-25 08:28 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +логгер это увидит и перестанет слать логи.
Исправил описание, расширил пример.

2023-10-25 08:29 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Чтобы создать реестр, необходимо вызвать его конструктор, передав функцию очистки (финализатор) в качестве аргумента.
Исправил раздел, добавил описание параметров и методов.

2023-10-25 08:29 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +```js run
Исправил.

2023-10-25 08:29 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +const getCachedImg = weakRefCache(fetchImg);
Исправил как и в примере выше.

2023-10-25 08:29 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +- `(1)` Для управления очисткой "мертвых" записей в кэше, когда связанные с ними объекты `WeakRef` собираются сборщиком мусора, создаём реестр очистки с использованием конструктора `FinalizationRegis
Исправил.

2023-10-25 08:29 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/weakref-finalizationregistry-03.svg
Исправил.

2023-10-25 08:29 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/weakref-finalizationregistry-06.svg
Исправил.

2023-10-25 08:30 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Важным моментом в реализации выше является то, что финализаторы внедряют параллелизм между "основной" программой и колбэками очистки.
Исправил, добавил более понятное описание и объяснение.

2023-10-25 08:30 UTC, WOLFRIEND commented on 1-js/05-data-types/09-weakref-finalizationregistry/article.md
> +Давайте представим, что мы хотим создать коллаж из 4-х фотографий, выбираем их, и нажимаем кнопку «Create collage».
Исправил.

2023-10-25 08:35 UTC, WOLFRIEND commented
Добрый день,

Я внёс изменения в соответствии с вашими правками:
1. Принял ваши рекомендации.
2. Исправил перевод текста в необходимых местах (картинки, примеры).
3. Устранил ошибки, исправил непонятные описания и объяснения в соответствии с вашими комментариями.
4. Перенёс статью в раздел, который вы предложили.
5. Добавил необходимые предупреждения.

Я старался максимально следовать вашим правкам и комментариям. Пожалуйста, оцените результат и скажите, нужны ли дополнительные правки к материалу? Спасибо за вашу помощь!

2023-10-29 00:19 UTC, Alexandre887 requested changes

2023-10-29 00:19 UTC, Alexandre887 commented on 1-js/99-js-misc/09-weakref-finalizationregistry/article.md
> +
Здесь очень неплохо было бы вставить скриншот "Photo Library Collage" без открытой консоли, чтобы можно было увидеть весь проект. Скриншот такого же размера, как и те, которые идут далее в статье. Без выбранных фотографий, без ничего - просто в том виде, в котором посетитель этого сайта встречает его, как только заходит.

Можете просто в папку загрузить, тогда я сам отправлю коммит с интеграцией изображения в статью.

2023-10-29 00:19 UTC, Alexandre887 commented on 1-js/99-js-misc/09-weakref-finalizationregistry/article.md
> +На этом этапе наша функция <code>weakCache</code> проверяет, есть ли нужное изображение в кеше. Если нет, то скачивает его из облака и помещает в кеш для возможности дальнейшего использования. И так
`weakCache`? Возможно, вы имели в виду `weakRefCache` (из примера со слабым кешированием)?

2023-10-29 00:19 UTC, Alexandre887 commented on 1-js/99-js-misc/09-weakref-finalizationregistry/article.md
> +![](weakref-finalizationregistry-demo-04.gif)
На предыдущем этапе (weakref-finalizationregistry-demo-03.jpg) было выбрано 4 изображения из 1 строки. На этом этапе (weakref-finalizationregistry-demo-04.jpg) выбрано 3 изображения из 1 строки (они входят в число тех, которые были выбраны на предыдущем этапе), а также 1 изображение из 2 строки. 

Но, в консоли `CACHED_IMAGE` говорит о том, что было взято из слабого кеша только 1 изображение - четвёртое в первой строке, с самолётом. Хотя по идее, из слабого кеша программа должна была взять все три изображения из первой строки, т.к. они уже были выбраны на предыдущем этапе.

Возможно, я что-то неправильно понимаю?

2023-10-30 13:46 UTC, WOLFRIEND commented on 1-js/99-js-misc/09-weakref-finalizationregistry/article.md
> +  Это может произойти не сразу и зависит только от внутренних механизмов сборщика мусора.
Исправил.

2023-10-30 13:46 UTC, WOLFRIEND commented on 1-js/99-js-misc/09-weakref-finalizationregistry/article.md
> +![](google-chrome-developers-tools-01.png)
Добавил.

2023-10-30 13:46 UTC, WOLFRIEND commented on 1-js/99-js-misc/09-weakref-finalizationregistry/article.md
> +
Добавил.

2023-10-30 13:46 UTC, WOLFRIEND commented on 1-js/99-js-misc/09-weakref-finalizationregistry/article.md
> +На этом этапе наша функция <code>weakCache</code> проверяет, есть ли нужное изображение в кеше. Если нет, то скачивает его из облака и помещает в кеш для возможности дальнейшего использования. И так
Исправил.

2023-10-30 13:55 UTC, WOLFRIEND commented
/done

2023-10-30 13:55 UTC, WOLFRIEND commented
Добрый день,

Я внёс изменения в соответствии с вашими правками и ответил в комментариях.

2023-10-31 00:47 UTC, Alexandre887 approved these changes

2023-10-31 00:47 UTC, merged