fix square brackets
javascript-tutorial/ru.javascript.info pull request #1924
Opened 2024-01-23 12:51 UTC by mikayel00

## Описание

Неправильно были поставлены квадратные скобки для optional параметров.

2024-01-23 15:37 UTC, Alexandre887 requested changes

2024-01-23 15:37 UTC, Alexandre887 commented on 1-js/05-data-types/12-json/article.md
> +let json = JSON.stringify(value [, replacer, space])
```suggestion
let json = JSON.stringify(value[, replacer, space])
```

2024-01-23 15:37 UTC, Alexandre887 commented on 1-js/05-data-types/12-json/article.md
> +let value = JSON.parse(str [, reviver]);
```suggestion
let value = JSON.parse(str[, reviver]);
```

2024-01-24 06:57 UTC, mikayel00 commented
/done

2024-01-30 23:04 UTC, ruslauz approved these changes

2024-02-12 12:00 UTC, mikayel00 commented
@Alexandre887 any changes needed?

2024-02-12 20:18 UTC, Alexandre887 approved these changes

2024-02-12 20:18 UTC, merged