Забыли важное замечание
javascript-tutorial/ru.javascript.info pull request #1938
Opened 2024-03-07 17:51 UTC by Owyn

Выкинули предложение просто при переводе почему-то нужное

2024-03-07 17:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1938) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=1938) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=1938) it.</sub>

2024-03-09 11:08 UTC, ruslauz commented on 3-frames-and-windows/03-cross-window-communication/article.md
> +Правильный документ точно будет доступен когда сработает iframe.onload. Но он срабатывает только тогда, когда загрузится весь iframe со всеми его ресурсами.
```suggestion
Правильный документ точно будет доступен, когда сработает iframe.onload. Но он срабатывает только тогда, когда загрузится весь iframe со всеми его ресурсами.
```

2024-04-09 13:45 UTC, Alexandre887 requested changes

2024-04-09 13:45 UTC, Alexandre887 commented on 3-frames-and-windows/03-cross-window-communication/article.md
> +Правильный документ точно будет доступен, когда сработает iframe.onload. Но он срабатывает только тогда, когда загрузится весь iframe со всеми его ресурсами.
```suggestion
Правильный документ точно будет доступен, когда сработает `iframe.onload`. Но он срабатывает только тогда, когда загрузится весь ифрейм со всеми его ресурсами.
```

2024-04-09 13:46 UTC, Alexandre887 approved these changes
Спасибо 👍

2024-04-09 13:46 UTC, merged