1-js/07-object-properties/02-property-accessors
javascript-tutorial/ru.javascript.info pull request #249
Opened 2019-06-17 12:36 UTC by OliverWall

Жду обратной связи

2019-06-17 12:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=249) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=249) before we can accept your contribution.<br/><hr/>**smyagkov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=249) it.</sub>

2019-06-17 12:58 UTC, xcurveballx requested changes
Я предлагаю по тексту

data property - свойства-данные
accessor property - свойства-аксессоры

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Первый тип это *свойства данных (data properties)*. Мы уже знаем, как работать с ними. На самом деле, все свойства, которые мы использовали до текущего момента были свойствами данных.
Первый тип -- это *свойства-данные (data properties)*. Мы уже знаем, как работать с ними. На самом деле, все свойства, которые мы использовали до текущего момента, были свойствами-данными.

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Второй тип свойств мы еще не рассматривали. Это *свойства доступа (accessor properties)*. По своей сути это функции, которые используют для присвоения и получения значения, но во внешнем коде они выг
ещЁ
используются

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Сейчас, мы хотим добавить свойство объекта "fullName", которое должно стать "John Smith". Само собой, мы не хотим дублировать уже имеющуюся информацию. Мы можем реализовать это с использованием свойс
не надо , после сейчас

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Снаружи, свойство доступа выглядит как обычное свойство. В этом и заключается идея свойств доступа. Мы не хотим *вызывать* `user.fullName` как функцию, мы *читаем* как обычное свойство: геттер выполн
не надо , после снаружи

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +На данный момент, `fullName` имеет только геттер. Если попытаться присвоить значение свойству `user.fullName`, то это вызовет ошибку.
не надо , после момент

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Давайте исправим это добавив сеттер для `user.fullName`:
, добавив

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Как только свойство определено с помощью `get prop()` или `set prop()`, оно становится свойством доступа, а не свойством данных.
свойством-данным

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +- Если определен сеттер -- мы может установить свойство `object.prop=...`, иначе нет.
можем

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Дескрипторы свойств доступа отличаются в сравнении со свойствами данных.
по сравнению

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Геттеры/сеттеры можно использоваться как обертки над "реальными" значениями свойств, чтобы получить больше контроля над ними.
использовать
обЁртки

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Техничесски, внешний код все еще может получить доступ к имени напрямую с помощью `user._name`, но существует широко известное соглашение о том, что свойства, которые начинаются с симовала `"_"` явля
Технически
с символа
, являются
, и к ним не следует обращаться из-за пределов объекта

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Одна отличная идея за геттерами и сеттерами -- они позволяют взять под контроль "обычные" свойства данных и корректировать их в любой момент.
Одна из хороших идей, стоящих за геттерами ...

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Пример, ранее мы начали реализовывать объект `user` используя свойства данных `name` и `age`:
Например,
, используя

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +...Но рано или поздно, все может измениться. Взамен `age` мы можем решить хранить `birthday`, потому что так более точно и удобно:
Но рано или поздно всё может измениться.

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Что нам делать со старым кодом который использует свойство `age`?
, который

2019-06-17 12:58 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Мы можем попытаться найти все такие места и изменить их, но это отнимает время и может быть тяжело выполнимо, если этот код был написан другими людьми. И кроме того, `age` это отличное свойство для `
-- это

2019-06-18 05:31 UTC, OliverWall commented
Внесены правки, прошу обратить внимание на склонения словосочетания свойства-аксессоры в тексте.

2019-06-18 05:49 UTC, OliverWall commented
/done

2019-06-18 07:39 UTC, xcurveballx reviewed
@OliverWall  ммм...большинство правок отсутствуют. Они не все показаны сразу - часть в свернутом виде. И также в словах свойства-данные и свойства-аксессоры склоняются обе части, т.е. пишем о свойствАХ-даннЫХ, относится к свойствУ-аксессорУ и т.п.

2019-06-18 07:39 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Первый тип это *свойства-данные (data properties)*. Мы уже знаем, как работать с ними. На самом деле, все свойства, которые мы использовали до текущего момента были свойствами-данных.
свойствами-данными

2019-06-18 07:39 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
>  Давайте исправим это добавив сеттер для `user.fullName`:
, добавив

2019-06-18 07:39 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Как только свойство определено с помощью `get prop()` или `set prop()`, оно становится свойством-аксессора, а не свойством-данных.
свойством-аксессором

2019-06-18 09:14 UTC, OliverWall commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Как только свойство определено с помощью `get prop()` или `set prop()`, оно становится свойством доступа, а не свойством данных.
очень странно звучит определение - свойством-данным.

2019-06-18 09:34 UTC, OliverWall commented
Большое спасибо за ревью, внесено большое количество правок согласно замечаниями.
Единственный вопрос. Предложенный вами вариант определения - свойства-данные в ед. числе - это "свойства данным", Возможно лучше подходит "свойства-данных"?

/done

2019-06-18 10:23 UTC, xcurveballx commented
@OliverWall Я думаю, что оба слова, свойство и данные, должны всегда стоять в одинаковом склонении. Само склонение зависит от ситуации:

говорим о (чем?) свойствах-данных
радуемся (чему?) свойствам-данным
записываем (что?) свойство-данное
и т.д.

Возможно, иногда это звучит немного странно, но если делать без тире, то вообще непонятно о чем речь.

2019-06-18 10:32 UTC, xcurveballx requested changes
Ок, еще 1 правка. На самом деле, чтобы не переделывать по 100 раз, я предлагаю оставить вопрос с переводом data property и accessor property для @iliakan 

PS  Я предложил

data property - свойства-данные
accessor property - свойства-аксессоры

2019-06-18 10:32 UTC, xcurveballx commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Технически, внешний код все еще может получить доступ к имени напрямую с помощью `user._name`, но существует широко известное соглашение о том, что свойства, которые начинаются с символа `"_"`, являю
всЁ ещЁ

2019-06-18 12:54 UTC, xcurveballx approved these changes

2019-06-18 14:00 UTC, iliakan requested changes
Спасибо за перевод! Пожалуйста, внеси изменения, улучшающие изложение =)

2019-06-18 14:20 UTC, OliverWall commented
Большое спасибо за ревью.
Правки внесены.

/done

2019-06-18 15:16 UTC, lex111 requested changes

2019-06-18 15:16 UTC, lex111 commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Первый тип это *свойства-данные (data properties - англ)*. Мы уже знаем, как работать с ними. Все свойства, которые мы использовали до текущего момента были свойствами-данными.
```suggestion
Первый тип это *свойства-данные (data properties)*. Мы уже знаем, как работать с ними. Все свойства, которые мы использовали до текущего момента были свойствами-данными.
```

2019-06-18 15:16 UTC, lex111 commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Свойства-аксессоры не имеют `value` и `writable`, но взамен предлагают `get` и `set` функции.
```suggestion
Свойства-аксессоры не имеют `value` и `writable`, но взамен предлагают функции `get` и `set`.
```

2019-06-18 15:16 UTC, lex111 commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Таким образом, дескриптор доступа может иметь:
```suggestion
Таким образом, дескриптор аксессора может иметь:
```

2019-06-18 15:16 UTC, lex111 commented on 1-js/07-object-properties/02-property-accessors/article.md
> +alert( john.age );      //  ...так и возраст
```suggestion
alert( john.age );      // ...так и возраст
```

2019-06-18 15:23 UTC, OliverWall commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Первый тип это *свойства-данные (data properties - англ)*. Мы уже знаем, как работать с ними. Все свойства, которые мы использовали до текущего момента были свойствами-данными.
В предыдущем ревью @iliakan предложил текущий вариант.

2019-06-18 15:53 UTC, lex111 commented on 1-js/07-object-properties/02-property-accessors/article.md
> +Первый тип это *свойства-данные (data properties - англ)*. Мы уже знаем, как работать с ними. Все свойства, которые мы использовали до текущего момента были свойствами-данными.
Выяснил у @iliakan, и решили убрать такие вставки, где возможно, поскольку это сразу понятно, если не указано иное, да и читать легче.

2019-06-18 16:28 UTC, OliverWall commented
/done

2019-06-18 16:47 UTC, iliakan commented
🚀

2019-06-18 16:47 UTC, merged