Замена
javascript-tutorial/ru.javascript.info pull request #855
Opened 2020-02-14 11:54 UTC by evgenstepanov

код использует текущую секунду пользователя.

2020-02-14 11:55 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=855) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=855) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/ru.javascript.info?pullRequest=855) it.</sub>

2020-07-24 05:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/javascript-tutorial/ru.javascript.info?pullRequest=855) <br/>All committers have signed the CLA.

2020-09-12 16:14 UTC, iliakan commented
Непонятная фраза получилась =(

2020-11-15 10:27 UTC, dandgerson requested changes

2020-11-15 10:27 UTC, dandgerson commented on 7-animation/2-css-animations/article.md
> +Если вы нажмёте на цифру ниже, то анимация начнётся с текущей секунды пользователя:
из англ. варианта
`Here if you click the digit -- it starts the animation from the current second:`

может так?
```suggestion
Если кликнуть по цифре ниже, то анимация начнётся с текущей секунды:
```

2020-11-16 07:40 UTC, closed without merging